name: 'airflow_with_dbt'
version: '1.0.0'

profile: 'airflow_with_cbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

vars:
    "dbt_date:time_zone": "America/Sao_Paulo"

clean-targets:
  - "target"
  - "dbt_packages"

models:
  airflow_with_dbt:
    staging:
      +materialized: view
    
    intermediate:
      +materialized: table
    
    mart:
      +materialized: table